{{- range .Values.virtualHosts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-ratelimit.fullname" $ }}-{{ .name }}
data:
  config-{{ .name }}.yaml:
{{ toYaml .config | indent 4 }}
{{- end }}
