{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-cluster
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.istio.workloadSelector }}
  workloadSelector:
{{ toYaml . | indent 4 }}
  {{- end }}
  configPatches:
    # The Envoy config you want to modify
    - applyTo: CLUSTER
      match:
        cluster:
          service: {{ include "go-ratelimit.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
      patch:
        operation: ADD
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          hosts:
            - socket_address:
                address: {{ include "go-ratelimit.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
                port_value: 8081
    # HTTP filter add
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND  # affect outbound traffic only
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.rate_limit
          config:
            # domain can be anything! Match it to the ratelimter service config
            domain: {{ .Values.istio.domain }}
            failure_mode_deny: {{ .Values.istio.failure_mode_deny }}
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
                timeout: 10s
  {{- end }}